apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: efinance
  namespace: argocd

spec:

  project: default

  source:
    repoURL: https://github.com/Akmal-Esmat/DevOps_efinance.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: efinance


  syncPolicy:

    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true