---
- name: Configure VM
  hosts: azure
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create apt keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker repository
      apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        filename: docker
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Add user to docker group
      user:
        name: akmal
        groups: docker
        append: yes

    - name: Enable Docker
      service:
        name: docker
        enabled: yes
        state: started

    - name: Create application directory
      file:
        path: /opt/ef-app
        state: directory
        mode: "0755"

    - name: Copy production compose file
      copy:
        src: files/compose.prod.yaml
        dest: /opt/ef-app/compose.yaml

    - name: Start application
      community.docker.docker_compose_v2:
        project_src: /opt/ef-app
        pull: always
        state: present