name: deploy to Dockerhub

on: 
  push:
    branches:
      - main

jobs:
  SCA:
    runs-on: ubuntu-latest
    steps:
        # The Checkout step clones the Git repository.
      - name: Checkout
        uses: actions/checkout@v7.0.0
        
      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          # fail if high/critical severity
          severity: HIGH,CRITICAL
          exit-code: '1'
  publish:
    runs-on: ubuntu-latest
    steps:

      # The Checkout step clones the Git repository again (each job is independent).
      - name: Checkout
        uses: actions/checkout@v7.0.0
        
      - name: Docker Login
        uses: docker/login-action@v4.2.0
        with:
            # Username to connect to Docker registry
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            # Password or token to connect to Docker registry
            password: ${{ secrets.DOCKERHUB_TOKEN }}
              
      - name: Build images
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: docker compose build
      
      - name: Show local images
        run: docker images
      
      - name: Tag frontend
        run: docker tag ef-frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/ef-frontend
      
      - name: Push frontend
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ef-frontend:latest

      - name: Tag backend
        run: docker tag ef-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/ef-backend

      - name: Push backend
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ef-backend:latest
